FROM apache/spark:3.5.7-scala2.12-java11-python3-r-ubuntu

USER root

RUN apt-get update && \
    apt-get install -y netcat && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER ${spark_uid}